spring.application.name=Spring-Boot_ModelMapper_MapStruct_Exception
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_modelmapper_mapstruct
spring.datasource.username=postgres
spring.datasource.password=112233